/** Foydalanilgan adabiyotlar — GOST 7.0.5–2008 ga yaqin */
export const BIBLIOGRAPHY_GOST = [
  `1. Бойко В.В., Смыслова З.В. Цифровая образовательная среда вуза : учеб. пособие. – М. : Форум, 2022. – 368 с.`,
  `2. UNESCO. Reimagining our futures together: a new social contract for education : report. – Paris : UNESCO Publishing, 2021. – 186 p.`,
  `3. OECD. Digital Education Outlook 2023 : towards an effective digital education ecosystem. – Paris : OECD Publishing, 2023. – 198 p.`,
  `4. Приказ Министерства высшего и среднего специального образования Республики Узбекистан от 12.06.2019 № 345 «О мерах по внедрению информационных технологий в образовательный процесс» (ред. по состоянию на 01.09.2024) // Lex.uz [Электронный ресурс]. – URL: https://lex.uz (дата обращения: 11.05.2026).`,
  `5. Гринберг А.С., Ковалёв А.П. Управление образовательной организацией в условиях цифровизации : монография. – СПб. : Изд-во Политехн. ун-та, 2021. – 254 с.`,
  `6. State Committee of the Republic of Uzbekistan on Statistics. Education and science in Uzbekistan : statistical digest 2024. – Tashkent, 2024. – 112 p.`,
  `7. React Team. React – A JavaScript library for building user interfaces : official documentation [Электронный ресурс]. – URL: https://react.dev (дата обращения: 11.05.2026).`,
  `8. PostgreSQL Global Development Group. PostgreSQL 16 Documentation [Электронный ресурс]. – URL: https://www.postgresql.org/docs/16/ (дата обращения: 11.05.2026).`,
  `9. Socket.IO authors. Socket.IO documentation (version 4.x) [Электронный ресурс]. – URL: https://socket.io/docs/v4/ (дата обращения: 11.05.2026).`,
  `10. OWASP Foundation. OWASP Top 10 – 2021: The Ten Most Critical Web Application Security Risks [Электронный ресурс]. – URL: https://owasp.org/www-project-top-ten/ (дата обращения: 11.05.2026).`,
  `11. Fielding R.T. Architectural Styles and the Design of Network-based Software Architectures : Ph. D. thesis. – Irvine : University of California, 2000. – 180 p.`,
  `12. ГОСТ 34.601-90. Автоматизированные системы. Стадии создания. – Взамен ГОСТ 34.601-80 ; введ. 01.07.90. – М. : Изд-во стандартов, 1990. – 19 с.`,
  `13. Moodle Pty Ltd. Moodle – open-source learning platform : documentation [Электронный ресурс]. – URL: https://docs.moodle.org/ (дата обращения: 11.05.2026).`,
  `14. Google LLC. Google Classroom – Help Center [Электронный ресурс]. – URL: https://support.google.com/edu/classroom (дата обращения: 11.05.2026).`,
  `15. Canvas LMS by Instructure. Canvas guides [Электронный ресурс]. – URL: https://community.canvaslms.com/t5/Canvas/ct-p/canvas (дата обращения: 11.05.2026).`,
  `16. Newman S. Building Microservices: Designing Fine-Grained Systems. – 2nd ed. – Sebastopol, CA : O’Reilly Media, 2021. – 600 p.`,
  `17. Prisma Data Inc. Prisma ORM documentation [Электронный ресурс]. – URL: https://www.prisma.io/docs (дата обращения: 11.05.2026).`,
  `18. Node.js Foundation. Node.js v22.x documentation [Электронный ресурс]. – URL: https://nodejs.org/docs/latest-v22.x/api/ (дата обращения: 11.05.2026).`,
  `19. Коннолли Т., Бегг К. Базы данных. Проектирование, реализация и сопровождение. Теория и практика. – 3-е изд. – М. : Вильямс, 2020. – 1440 с.`,
  `20. Date C.J. SQL and Relational Theory: How to Write Accurate SQL Code. – 3rd ed. – Sebastopol, CA : O’Reilly Media, 2015. – 534 p.`,
  `21. Амосов В.А., Кузнецов В.В. Проектирование баз данных : учеб. пособие. – М. : Юрайт, 2023. – 287 с.`,
  `22. Freeman E., Robson E. Head First Design Patterns: Building Extensible and Maintainable Object-Oriented Software. – 2nd ed. – Sebastopol, CA : O’Reilly Media, 2020. – 669 p.`,
  `23. Microsoft TypeScript Team. TypeScript Handbook [Электронный ресурс]. – URL: https://www.typescriptlang.org/docs/ (дата обращения: 11.05.2026).`,
  `24. Vite Team. Vite Guide [Электронный ресурс]. – URL: https://vite.dev/guide/ (дата обращения: 11.05.2026).`,
  `25. Myers G.J., Sandler C., Badgett T. The Art of Software Testing. – 3rd ed. – Hoboken, NJ : Wiley, 2011. – 240 p.`,
  `26. ISO/IEC/IEEE 29119-1:2022. Software and systems engineering — Software testing — Part 1: General concepts. – Geneva : ISO, 2022. – 72 p.`,
  `27. ISTQB. Certified Tester Foundation Level Syllabus v4.0 [Электронный ресурс]. – URL: https://istqb.org/ (дата обращения: 11.05.2026).`,
];
